### ISSUE TITLE
Namespace Rhino.Mocks

### ISSUE THREAD

**Issue by gigi81** [minhhut/rhino-to-moq#1]
Hi,
Brilliant idea.
Just wondering why you are using the namespace RhinoMocksToMoq instead of "Rhino.Mocks" of the original library. if you change the namespace to the original library one, this would become a drop-in replacement.
Thanks

**Comment by minhhut** [comment]
Thanks for your kindly words, this lib came out as i need to migrate about 400 test cases and i don't want to update one by one. I have pushed the update version 0.2.0 that has same namespace which still confuse with existing one but i would do if it helps people don't want to minimize the code change.
BR, Minh
